css_adjust_sort_browsers: false
css_adjust_sort_external: false
css_defer: 7
css_defer_admin: false
css_defer_js_code: 2
css_preprocess: false
css_translate: null
js_adjust_sort_browsers: false
js_adjust_sort_external: false
js_async: false
js_async_in_header: false
js_defer: 0
js_get_external_dns: null
js_footer: 0
js_preprocess: false
prefetch: null
unified_multisite_dir: ''
_core:
  default_config_hash: K1LjGu1pf32pW_spWyBUfP4uJILVnK0p9-74sKbSxmo
ga_inline_to_file: null
